### ISSUE TITLE
resize instance

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#162]
Need help.. I'm trying to resize an instance on same compute node and I'm getting following err. 

So far I tied with following changes in nova.conf file on compute node. Still no luck.

allow_resize_to_same_host=True
scheduler_default_filters=AllHostsFilter
allow_migrate_to_same_host=True

I'm using puppet modules v4.2.0

" conductor.log "
2015-03-13 23:48:02.583 3487 WARNING nova.scheduler.utils [req-6ccd63e7-58f1-47dc-9c45-623c095faa49 cc73301018d44104a0a76c4a94512565 7
80221eb5f9f44adbdd7f510306afb77] Failed to compute_task_migrate_server: No valid host was found.
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/oslo/messaging/rpc/server.py", line 139, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.6/site-packages/nova/scheduler/manager.py", line 298, in select_destinations
    filter_properties)

  File "/usr/lib/python2.6/site-packages/nova/scheduler/filter_scheduler.py", line 140, in select_destinations
    raise exception.NoValidHost(reason='')

NoValidHost: No valid host was found.

2015-03-13 23:48:02.584 3487 WARNING nova.scheduler.utils [req-6ccd63e7-58f1-47dc-9c45-623c095faa49 cc73301018d44104a0a76c4a94512565 7
80221eb5f9f44adbdd7f510306afb77] [instance: 2a877215-9a8c-47b5-8cae-9962c897990b] Setting instance to ACTIVE state.
2015-03-13 23:48:02.679 3487 WARNING nova.conductor.manager [req-6ccd63e7-58f1-47dc-9c45-623c095faa49 cc73301018d44104a0a76c4a94512565
 780221eb5f9f44adbdd7f510306afb77] [instance: 2a877215-9a8c-47b5-8cae-9962c897990b] No valid host found for cold migrate

**Comment by cmurphy** [comment]
This doesn't seem to be specifically related to this puppet module, and I'm not an expert on nova configuration or resizing instances. I would recommend asking on the openstack mailing list. If you can identify a configuration error that is produced by this module we can look at workarounds and bugfixes.

I'd also recommend using the latest stable/juno versions of these modules rather than the 4.x (icehouse) versions, if you're able to upgrade. However I can't say if that relates to this issue.
